name: Build and Push Docker Image

# This action will trigger on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Check out repo
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      # This uses the secrets you need to add to your GitHub repository settings
      # Go to Repo > Settings > Secrets and variables > Actions > New repository secret
      # DOCKERHUB_USERNAME: Your Docker Hub username
      # DOCKERHUB_PASSWORD: Your Docker Hub password
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # This creates two tags: 'latest' and one with the Git commit SHA
          tags: |
            dpooper79/homepagerr:latest
            dpooper79/homepagerr:${{ github.sha }}